name: Send message
on:
 schedule:
   - cron: "0 1 * * "
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Send message
      run: curl ntfy.sh -d "Hello from GitHub actions workflow"